language: node_js
node_js:
- '8'
after_success:
      - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: npm
  email: peter@terascope.io
  api_key:
    secure: DyM0NwdACUMIs/FAYBgRcUS05uUmTS6Oxh7Z2bkV/Mu21fnucnDqHRUOtNUrBr3LULRP2JHDUR3m1102Gp8sfynJqIvgWq1r0Vsyusq3xNiqWQAxbCRZpAjBw8GtQyB77m08pZ7NY4qQCi1X2l6RHxls8P4AECWjAgy6yqeQTGszvbyQVvRDu8BdAlyTRertHnmhZSFXcTY5qrkzhWCKerIfV07hA4+XG/ckPnSf3mEYBnoa/awvBkWLBAO627ALgfC48GDF8u8vUNpKmoAV6xZTz5i6rnLBOxIkuC64Us4ZKWvOjsFp5UVMrFya+aWsrg58dtecve4gpviqD19PoATSL/9aQh7tVSC+ezFSC/YdHv4RfbMul+3Xp2YWRVDmY0LqFGxkNRJdkk7vroZeZ0ocbE2lRseNv3YbLYP29F1IllSiy6XArsFJaL1rTIOmPCOMjgMsD4I0HJuf4f0eEcc3QmuOzBGcB4mBnQVwcP+Wn1mxj1dxivgvRHq+DpbzqqS/3fm/dVKzDrSScAylGWpq7jxnHmichBiCczABWtneg96qE0I9Dq010SvpbEY6zQED6Anmi+aU7hhmaAWzJLdRPfAPhxs/vKwiYmCCty+iKF8pBdnZoqK40xjgjavSMPJ6e4/eF3kj4U0x4EYNPI+vF8EKrqk7TyzWliCAy7s=
  on:
    tags: true
    repo: terascope/xlucene-evaluator
